# .github/workflows/reusable-docs-build.yml
# 목적: Doxygen 문서를 생성하고 GitHub Pages 배포용 아티팩트를 업로드합니다.
name: Reusable - Generate Documentation

on:
  workflow_call:

jobs:
  docs_job:
    name: Generate and Upload Doxygen Docs
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Install Doxygen & Graphviz
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends doxygen graphviz && sudo rm -rf /var/lib/apt/lists/*
      - name: Generate Documentation
        run: doxygen ./docs/Doxyfile
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # 경로 주의: Doxyfile의 OUTPUT_DIRECTORY + html 하위 경로가 맞는지 최종 확인 필요!
          path: ./docs/docs_output/html