# .github/workflows/reusable-deploy-aws.yml
# 목적: ECR에 푸시된 이미지를 사용하여 AWS ECS (EC2 유형) 서비스를 업데이트합니다.
name: Reusable - Deploy to AWS ECS (EC2 Type)

on:
  workflow_call:
    # 입력값 정의
    inputs:
      aws_region:
        required: true
        type: string
      image_name_ecr:
        required: true
        type: string
      image_tag:
        required: true
        type: string
        description: 배포할 고유 태그 (SHA)
      container_name:
        required: true
        type: string
      server_port_value:
        required: true
        type: string
        default: "8080"
      task_definition_template_path:
        required: true
        type: string
      ecs_cluster_name:
        required: true
        type: string
      ecs_service_name:
        required: true
        type: string
    # 비밀값 정의
    secrets:
      aws_role_to_assume:
        required: true
      task_execution_role_arn:
        required: true

jobs:
  deploy_job:
    name: Deploy to AWS ECS
    runs-on: ubuntu-latest
    # OIDC 인증 및 템플릿 파일 읽기 권한
    permissions:
      id-token: write
      contents: read

    steps:
      # 1. 소스 코드 체크아웃 (템플릿 파일 접근 위해)
      - name: Check out source code
        uses: actions/checkout@v4

      # 2. AWS 자격 증명 설정 (OIDC)
      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws_role_to_assume }}
          aws-region: ${{ inputs.aws_region }}
          role-session-name: GitHubActions-Deploy-${{ github.run_id }}

      # 3. 태스크 정의 템플릿 렌더링 (jq 사용)
      - name: Render task definition template
        run: |
          jq --arg server_port_value "${{ inputs.server_port_value }}" \
             --arg image "${{ inputs.image_name_ecr }}:${{ inputs.image_tag }}" \
             --arg family "${{ vars.ECS_TASK_DEF_FAMILY }}" \
             --arg execution_role_arn "${{ secrets.task_execution_role_arn }}" \
             --arg container_name "${{ inputs.container_name }}" \
             --arg aws_region "${{ inputs.aws_region }}" \
             '.
              | .family = $family
              | .executionRoleArn = $execution_role_arn
              | .containerDefinitions[0].name = $container_name
              | .containerDefinitions[0].image = $image
              | .containerDefinitions[0].portMappings[0].containerPort = ($server_port_value | tonumber)
              | .containerDefinitions[0].environment[0].value = $server_port_value
              | .containerDefinitions[0].logConfiguration.options."awslogs-group" = "/ecs/" + $family
              | .containerDefinitions[0].logConfiguration.options."awslogs-region" = $aws_region
             ' ${{ inputs.task_definition_template_path }} > rendered.json

      # 4. 태스크 정의 등록
      - name: Register task definition
        id: register-task
        run: |
          TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json file://rendered.json --query 'taskDefinition.taskDefinitionArn' --output text)
          echo "task_def_arn=$TASK_DEF_ARN" >> $GITHUB_OUTPUT

      # 5. ECS 서비스 업데이트
      - name: Update ECS service
        run: |
          aws ecs update-service --cluster ${{ inputs.ecs_cluster_name }} --service ${{ inputs.ecs_service_name }} --task-definition ${{ steps.register-task.outputs.task_def_arn }}