# .github/workflows/reusable-docker-push-ecr.yml
# 목적: 빌드된 Docker 이미지를 AWS ECR로 푸시합니다. OIDC로 인증합니다.
name: Reusable - Push Docker Image to ECR

on:
  workflow_call:
    inputs:
      image_name_ecr: { required: true, type: string }
      image_tag_sha: { required: true, type: string }
      image_tag_latest: { required: true, type: string }
      aws_region: { required: true, type: string }
      image_digest_built: # 빌드된 로컬 이미지 태그 (예: localbuild:sha-...)
        required: true
        type: string
      ghcr_image_uri_sha: # GHCR 이미지 전체 URI + SHA 태그 (예: ghcr.io/owner/repo:sha-...)
        required: true
        type: string
    secrets:
      aws_role_to_assume: { required: true }

jobs:
  push_ecr_job:
    name: Pull GHCR, Check Digest, Push to ECR
    runs-on: ubuntu-latest
    permissions:
      id-token: write # OIDC 필수 권한
      packages: read  # GHCR 이미지 풀링 권한

    steps:
      # 1. AWS 자격 증명 설정 (OIDC)
      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws_role_to_assume }}
          aws-region: ${{ inputs.aws_region }}
          role-session-name: GitHubActions-ECR-Push-${{ github.run_id }}

      # 2. ECR 로그인
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

     # 3. GHCR 로그인 (Public은 불필요, Private은 PAT 또는 GITHUB_TOKEN 필요)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }} # Public/Internal repo용 기본 토큰
        
      # 4. ECR의 :latest 태그 다이제스트 조회 (오류 무시)
      - name: Get ECR :latest image digest
        id: get-latest-digest
        run: |
          ECR_IMAGE_LATEST="${{ inputs.image_name_ecr }}:latest"
          # manifest inspect는 이미지가 없으면 오류 발생, || true로 오류 무시하고 결과 저장
          LATEST_DIGEST=$(docker manifest inspect $ECR_IMAGE_LATEST --verbose 2>/dev/null | jq -r '.Descriptor.digest // ""' || echo "")
          echo "Current :latest digest in ECR: $LATEST_DIGEST"
          echo "latest_digest=$LATEST_DIGEST" >> $GITHUB_OUTPUT
        shell: bash

      # 5. 다이제스트 비교 및 푸시 결정
      - name: Check digests and set push flag
        id: check-push
        run: |
          BUILT_DIGEST="${{ inputs.image_digest_built }}"
          LATEST_DIGEST="${{ steps.get-latest-digest.outputs.latest_digest }}"
          echo "Built Digest: $BUILT_DIGEST"
          echo "Latest Digest: $LATEST_DIGEST"
          if [ "$BUILT_DIGEST" != "$LATEST_DIGEST" ] || [ -z "$LATEST_DIGEST" ]; then
            echo "Digests differ or :latest not found. Push required."
            echo "push_required=true" >> $GITHUB_OUTPUT
          else
            echo "Digests match. No push required."
            echo "push_required=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      # --- 6. 이미지 Pull, Tag, Push (조건부 실행) ---
      - name: Pull from GHCR, Tag, and Push image to ECR
        if: steps.check-push.outputs.push_required == 'true'
        env:
          ECR_IMAGE_BASE: ${{ inputs.image_name_ecr }}
          TAG_SHA: ${{ inputs.image_tag_sha }}
          TAG_LATEST: ${{ inputs.image_tag_latest }}
          GHCR_IMAGE_SHA: ${{ inputs.ghcr_image_uri_sha }} # Pull 대상 이미지 (SHA 태그 포함)
        run: |
          echo "Pulling image from GHCR: $GHCR_IMAGE_SHA"
          docker pull $GHCR_IMAGE_SHA # <-- GHCR에서 이미지 가져오기
          if [ $? -ne 0 ]; then echo "Error: Failed to pull image from GHCR"; exit 1; fi

          # 이제 로컬에 $GHCR_IMAGE_SHA 태그로 이미지가 존재함
          echo "Tagging $GHCR_IMAGE_SHA -> $ECR_IMAGE_BASE:$TAG_SHA and $ECR_IMAGE_BASE:$TAG_LATEST"
          docker tag $GHCR_IMAGE_SHA $ECR_IMAGE_BASE:$TAG_SHA
          docker tag $GHCR_IMAGE_SHA $ECR_IMAGE_BASE:$TAG_LATEST

          echo "Pushing $ECR_IMAGE_BASE:$TAG_SHA"
          docker push $ECR_IMAGE_BASE:$TAG_SHA

          echo "Pushing $ECR_IMAGE_BASE:$TAG_LATEST"
          docker push $ECR_IMAGE_BASE:$TAG_LATEST
        shell: bash

      # 7. 푸시 건너뛰기 메시지 (조건부 실행)
      - name: Image push skipped
        if: steps.check-push.outputs.push_required == 'false'
        run: echo "Image content has not changed. Skipping ECR push."
        shell: bash