# .github/workflows/reusable-docker-push-dh.yml
# 목적: 빌드된 Docker 이미지를 Docker Hub로 푸시합니다. Access Token으로 인증합니다.
name: Reusable - Push Docker Image to Docker Hub

on:
  workflow_call:
    inputs:
      image_name_dh: { required: true, type: string }
      image_tag_sha: { required: true, type: string }
      image_tag_latest: { required: true, type: string }
      ghcr_image_uri: { required: true, type: string }
    secrets:
      dockerhub_username: { required: true }
      dockerhub_token: { required: true } # Access Token

jobs:
  push_dh_job:
    name: Push Image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      # GitHub 컨테이너 레지스트리 로그인
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      
      # GHCR에서 이미지 가져오기
      - name: Pull image from GHCR
        env:
          GHCR_IMAGE: ${{ inputs.ghcr_image_uri }}
        run: |
          echo "Using image: $GHCR_IMAGE"
          docker pull $GHCR_IMAGE

      # 1. Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_token }} # Access Token 사용

      # 2. Docker 이미지 푸시 (두 태그 모두)
      - name: Push Docker image to Docker Hub
        env:
          DH_IMAGE_NAME: ${{ inputs.image_name_dh }}
          IMAGE_TAG_SHA: ${{ inputs.image_tag_sha }}
          IMAGE_TAG_LATEST: ${{ inputs.image_tag_latest }}
          GHCR_IMAGE: ${{ inputs.ghcr_image_uri }}
        run: |
          set -e # 명령어 실패 시 중단
          docker tag $GHCR_IMAGE $DH_IMAGE_NAME:$IMAGE_TAG_SHA
          docker tag $GHCR_IMAGE $DH_IMAGE_NAME:$IMAGE_TAG_LATEST
          echo "Pushing image: $DH_IMAGE_NAME:$IMAGE_TAG_SHA"
          docker push $DH_IMAGE_NAME:$IMAGE_TAG_SHA
          echo "Pushing image: $DH_IMAGE_NAME:$IMAGE_TAG_LATEST"
          docker push $DH_IMAGE_NAME:$IMAGE_TAG_LATEST